name: 'main-merge'

on:
  push:
    branches:
    - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          ref: main
          
  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: ls1
        run: ls -lrt
      - name: Init
        uses: actions/checkout@v3
        with:
          ref: main
      - name: ls2
        run: ls -lrt

      - name: Install Dependencies
        working-directory: ./seetoday-web
        run: yarn

      - name: Build
        working-directory: ./seetoday-web
        run: yarn build
      
      - name: Cache
        uses: actions/cache@v3.0.11
        with: 
          path: dist
          key: build-files
        
  deploy:
    runs-on: ubuntu-latest
    needs: [checkout, build]
    steps:
      - name: Deploy 
        working-directory: ./seetoday-web
        env:
          # secrets 를 통해 github 비밀키에 접근 가능하다.
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        run: |
          aws s3 sync --region ap-northeast-2 ./dist s3://see-today --acl public-read --follow-symlinks --delete
