name: 'main-merge'

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          ref: main
          
      - name: Install Dependencies
        working-directory: ./seetoday-web
        run: yarn

      - name: Build
        working-directory: ./seetoday-web
        run: yarn build
      
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: build-dist
          path: ./seetoday-web/dist
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: build-dist
          
      - name: Debug
        run: ls -lrt
          
      - name: Deploy 
        env:
          # secrets 를 통해 github 비밀키에 접근 가능하다.
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        run: |
          aws s3 sync --region ap-northeast-2 ./ s3://see-today --acl public-read --follow-symlinks --delete
